//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechkaRU.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cart_id { get; set; }
        public int user_id { get; set; }
        public int medicine_id { get; set; }
        public int quantity { get; set; }
        public Nullable<System.DateTime> added_at { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual Users Users { get; set; }
    }
}
