//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechkaRU.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitMedicines
    {
        public int kit_medicine_id { get; set; }
        public int kit_id { get; set; }
        public int medicine_id { get; set; }
        public int quantity { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string notes { get; set; }
    
        public virtual UserMedicineKits UserMedicineKits { get; set; }
        public virtual Medicines Medicines { get; set; }
    }
}
