//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechkaRU.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineReviews
    {
        public int review_id { get; set; }
        public int user_id { get; set; }
        public int medicine_id { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
        public System.DateTime review_date { get; set; }
        public bool is_approved { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual Users Users { get; set; }
    }
}
