//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechkaRU.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicines()
        {
            this.Cart = new HashSet<Cart>();
            this.Favorites = new HashSet<Favorites>();
            this.KitMedicines = new HashSet<KitMedicines>();
            this.PurchasedMedicines = new HashSet<PurchasedMedicines>();
            this.Reminders = new HashSet<Reminders>();
        }
    
        public int medicine_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int manufacturer_id { get; set; }
        public int category_id { get; set; }
        public decimal price { get; set; }
        public Nullable<bool> requires_prescription { get; set; }
        public Nullable<int> stock_quantity { get; set; }
        public string image_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorites> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitMedicines> KitMedicines { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual MedicineCategories MedicineCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasedMedicines> PurchasedMedicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reminders> Reminders { get; set; }
        public string CurrentPhoto
        {
            get
            {
                if (String.IsNullOrEmpty(image_url) || String.IsNullOrWhiteSpace(image_url))
                {
                    return "/Images/picture.jpg";
                }
                else
                {
                    return "/Images/" + image_url;
                }
            }
        }
    }
}
