//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechkaRU.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AptechkaRUEntities1 : DbContext
    {
        public AptechkaRUEntities1()
            : base("name=AptechkaRUEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<KitMedicines> KitMedicines { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<MedicineCategories> MedicineCategories { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<Pharmacies> Pharmacies { get; set; }
        public virtual DbSet<PurchasedMedicines> PurchasedMedicines { get; set; }
        public virtual DbSet<PurchaseHistory> PurchaseHistory { get; set; }
        public virtual DbSet<Reminders> Reminders { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserMedicineKits> UserMedicineKits { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
