//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechkaRU.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseHistory()
        {
            this.PurchasedMedicines = new HashSet<PurchasedMedicines>();
        }
    
        public int purchase_id { get; set; }
        public int user_id { get; set; }
        public int pharmacy_id { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public decimal total_amount { get; set; }
    
        public virtual Pharmacies Pharmacies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasedMedicines> PurchasedMedicines { get; set; }
        public virtual Users Users { get; set; }
    }
}
