//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechkaRU.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedMedicines
    {
        public int purchased_medicine_id { get; set; }
        public int purchase_id { get; set; }
        public int medicine_id { get; set; }
        public int quantity { get; set; }
        public decimal price_per_unit { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual PurchaseHistory PurchaseHistory { get; set; }
    }
}
