//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechkaRU.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminders
    {
        public int reminder_id { get; set; }
        public int user_id { get; set; }
        public int medicine_id { get; set; }
        public Nullable<int> kit_id { get; set; }
        public string dosage { get; set; }
        public string frequency { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual UserMedicineKits UserMedicineKits { get; set; }
        public virtual Users Users { get; set; }
    }
}
